### ISSUE TITLE
使用webpack-coc 的demo的问题

### ISSUE THREAD

**Issue by mingliao** [jzlxiaohei/webpack-coc-example#1]
你好，请问下，我在使用webpack-coc的例子的时候，在basic-example的src下的contact文件夹下添加了contact.css但是build的时候为什么在dist下没有相应的文件出现？

**Comment by mingliao** [comment]
不好意思，是我自己没有按需加载，contact.js文件中没有import相应的文件。

**Comment by jzlxiaohei** [comment]
@mingliao 感谢使用，这个东西我这边已经用在生产了，但是我只想说，生产上的各种乱七八糟的问题太多，当然这个东西是我写的，我都能圆回来。最近我也在思考怎么把这个项目拆的更好理解。

建议你还是先看看我的教程和源码，撸一个自己够用的。其实不难，关键撸完，万一你的生产上有各种问题，自己也能搞定。
